apiVersion: 1

datasources:

  - access: proxy
    basicAuth: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    editable: true
    isDefault: true
    name: loki
    type: loki
    uid: loki
    url: http://loki-gateway:80
    version: 1

  - access: proxy
    basicAuth: false
    editable: true
    isDefault: false
    name: prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    version: 1

  - access: proxy
    url: http://tempo-query-frontend:3200
    basicAuth: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
    editable: true
    isDefault: false
    name: tempo
    type: tempo
    uid: tempo
    version: 1
