server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3200
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095

  register_instrumentation: true

distributor:
  receivers:
    zipkin:

ingester:
  lifecycler:
    ring:
      replication_factor: 3
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - ingester-0:7946
  - ingester-1:7946
  - ingester-2:7946

compactor:
  compaction:
    block_retention: 1h

query_frontend:
    max_retries: 2

querier:
  frontend_worker:
    frontend_address: query-frontend:9095

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo
      endpoint: minio:9000
      access_key: admin
      secret_key: testtesttest
      insecure: true
    wal:
      path: /tmp/tempo/wal
      v2_encoding: snappy
    pool:
      max_workers: 100
      queue_depth: 10000

overrides:
  defaults:
    metrics_generator:
      processors: ['service-graphs', 'span-metrics']
